### ISSUE TITLE
verified badge

### ISSUE THREAD

**Issue by shawny43** [gwillem/freeflarum.com#301]
__Packagist URL for extension:__
https://packagist.org/packages/serakoi/flarum-verified-badge

__Why should we install the extension?__

Get real verified badge in server.

**Comment by CWKevo** [comment]
All that extension does is that it just adds a JavaScript to display the verified badge.
https://github.com/Seer-Software-Dev/flarum-verified-badge/blob/main/extend.php

Does this extension offer anything else that you wouldn't get from just creating a group and using `fas fa-check` as icon? https://fontawesome.com/v5.15/icons/check?style=solid

**Comment by Kaleb99jOfficial** [comment]
@CWKevo I was curious so I looked at the [Discuss](https://discuss.flarum.org/d/27527-simple-verified-badge) for it and all it does is add the JavaScript and allow you to create a group but instead of using a FontAwesome name, you use verifiedBadge. It seems the creator is new to creating PHP plugins and seen that some people wanted a "proper" verified badge.

**Comment by CWKevo** [comment]
> @CWKevo I was curious so I looked at the [Discuss](https://discuss.flarum.org/d/27527-simple-verified-badge) for it and all it does is add the JavaScript and allow you to create a group but instead of using a FontAwesome name, you use verifiedBadge. It seems the creator is new to creating PHP plugins and seen that some people wanted a "proper" verified badge.

That was one of the points I was trying to make. I think that this is something that you can do by yourself, without any extension. FreeFlarum is quite encumbered with extensions at this point, so I would like to only include features that are unique or that do not have a heavy backend code.

**Comment by CWKevo** [comment]
I won't include this, as all this does is that it adds this code into `<head>`:

```html
<script>
    window.addEventListener("load", function(){
        const vBadges = document.getElementsByClassName("verifiedBadge");
        if(vBadges.length > 0){
            for(const b of vBadges){
                const parentBadge = b.parentElement;
                parentBadge.classList.add("verifiedBadgeParent");
            }
        }
    });
</script>
```

CSS:

```css
.verifiedBadgeParent {
    background-color: transparent !important;
}
.badges {
    list-style-image: initial;
}
.verifiedBadge {
    line-height: 21px;
    text-align: center;
    font-size: 12.32px;
    box-shadow: none!important;
    margin-left: 0px !important;
    background-image: url(https://seer-software.com/svg/verified.svg);
    background-color: initial;
    background-size: 100% auto;
    display: block;
    height: 100%;
    width: auto;
    background-repeat: no-repeat;
}
.verifiedBadgeBlue {
    line-height: 21px;
    text-align: center;
    font-size: 12.32px;
    box-shadow: none!important;
    margin-left: 0px !important;
    background-image: url(https://seer-software.com/svg/verified-blue.svg);
    background-color: initial;
    background-size: 100% auto;
    display: block;
    height: 100%;
    width: auto;
    background-repeat: no-repeat;
}
```

I encourage forum admins to individually put these codes in your admin settings to replicate the extension's functionality instead.
